name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind_tests:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master

      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.14.0"

      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

      - name: Get pachctl
        run: curl -o /tmp/pachctl.deb -L https://github.com/pachyderm/pachyderm/releases/download/v2.3.9/pachctl_2.3.9_amd64.deb && sudo dpkg -i /tmp/pachctl.deb  


      - name: Helm it up
        run: |
          helm repo add pach https://helm.pachyderm.com  
          helm repo update 

      - name: Run pach
        run: helm install --wait --timeout 10m pachd pach/pachyderm --set deployTarget=LOCAL  

      - name: Trust but verify
        run: |
          kubectl get pods
          pachctl config import-kube local --overwrite
          pachctl config set active-context local
          pachctl port-forward &
          sleep 5
          pachctl version
          curl 'localhost:4000'

